#!/bin/sh

# Public domain notice for all NCBI EDirect scripts is located at:
# https://www.ncbi.nlm.nih.gov/books/NBK179288/#chapter6.Public_Domain_Notice

dbase=""
flag="none"
target=""

while [ $# -gt 0 ]
do
  case "$1" in
    -strict )
      flag="strict"
      shift
      ;;
    -mixed )
      flag="mixed"
      shift
      ;;
    -db )
      dbase=$2
      shift
      shift
      ;;
    -* )
      exec >&2
      echo "$0: Unrecognized option $1"
      exit 1
      ;;
    * )
      break
      ;;
  esac
done

if [ -z "$dbase" ]
then
  echo "Must supply database in -db argument"
  exit 1
fi

MASTER=""

case "$dbase" in
    pubmed )
      MASTER="${EDIRECT_PUBMED_MASTER}"
      ;;
    pmc )
      MASTER="${EDIRECT_PMC_MASTER}"
      ;;
    taxonomy )
      MASTER="${EDIRECT_TAXONOMY_MASTER}"
      ;;
esac

if [ -z "${MASTER}" ]
then
  echo "Must supply path to archive files or set EDIRECT_XXX_MASTER environment variable"
  exit 1
else
  MASTER=${MASTER%/}
  target="$MASTER/Archive"
fi

osname=`uname -s | sed -e 's/_NT-.*$/_NT/; s/^MINGW[0-9]*/CYGWIN/'`
if [ "$osname" = "CYGWIN_NT" -a -x /bin/cygpath ]
then
  target=`cygpath -w "$target"`
fi

target=${target%/}

HEAD=$(cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
EOF
)

TAIL=$(cat <<EOF
EOF
)

echo "$HEAD"
rchive -gzip -db "$dbase" -flag "$flag" -fetch "$target"
echo "$TAIL"
