#!/bin/bash

# Public domain notice for all NCBI EDirect scripts is located at:
# https://www.ncbi.nlm.nih.gov/books/NBK179288/#chapter6.Public_Domain_Notice

xtract -stops -set IdxDocumentSet -rec IdxDocument -pattern PubmedArticle \
  -wrp IdxUid -element MedlineCitation/PMID -clr -rst -tab "" \
  -group PubmedArticle -pkg IdxSearchFields \
    -block InvestigatorList -wrp INUM -num Investigator/LastName \
    -block AuthorList -wrp FNUM -num AffiliationInfo/Affiliation \
    -block AffiliationInfo -wrp FLWD -pairs Affiliation |
transmute -format
